// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unpdsxtwubwmyalsiwjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVucGRzeHR3dWJ3bXlhbHNpd2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjM2MTAsImV4cCI6MjA2NDMzOTYxMH0._sSZkwox20b3ZZ3ObvF4Nqbq7-BoRSxJshFf6WtkTrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);